
---
######## Front install

 - name: Delete git front
   file:
     path=/var/www/
     state=absent

 - name: clone app repo
   git:
     repo: 'https://github.com/Mikhail-Dyuryagin/web-front'
     dest: /var/www/
   notify:
     - restart nginx


 - name: Delete git naher
   file: 
     path=/var/www/.git
     state=absent


