---
- hosts: all
  remote_user: root
  gather_facts: no
  become: false
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
  roles:
    - pre
    - git
    - nginx
    - web-front
    - goolang
    - git
    - api-sum    
